export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const checkValidConstants = {
    CHECK_VALID_REQUEST: "CHECK_VALID_REQUEST",
    CHECK_VALID_SUCCESS: "CHECK_VALID_SUCCESS",
    CHECK_VALID_FAILURE: "CHECK_VALID_FAILURE"

}

export const getResultConstants = {
    GET_RESULT_REQUEST: "GET_RESULT_REQUEST",
    GET_RESULT_SUCCESS: "GET_RESULT_SUCCESS",
    GET_RESULT_FAILURE: "GET_RESULT_FAILURE"

}

export const connectNodeConstants = {
    CONNECT_NODES_REQUEST : "CONNECT_NODES_REQUEST",
    CONNECT_NODES_SUCCESS : "CONNECT_NODES_SUCCESS",
    CONNECT_NODES_FAILURE : "CONNECT_NODES_FAILURE"

}

export const replaceChainConstants = {
    REPLACE_CHAIN_REQUEST: "REPLACE_CHAIN_REQUEST",
    REPLACE_CHAIN_SUCCESS: "REPLACE_CHAIN_SUCCESS",
    REPLACE_CHAIN_FAILURE: "REPLACE_CHAIN_FAILURE"

}